googleAnalytics = "UA-33668157-6"
baseURL =           "https://andron13.de/"
defaultContentLanguage = "ru"
languageCode =      "ru"
title =             "andron13"
theme =             "book"
disqusShortname =   "andron13-de"
paginate        =   6

# Book configuration
#disablePathToLower = true
#enableGitInfo = true

[params]
  BookToC = true
  BookLogo = 'logo.jpg'
  BookSection = 'school'
  BookMenuBundle = '/menu'
  images = ["site-feature-image.jpg"]
  AuthorName = "andron13"
  GitHubUser = "andron13"

#[privacy]
#  [privacy.disqus]
#    disable = false
#  [privacy.googleAnalytics]
#    anonymizeIP = false
#    disable = false
#    respectDoNotTrack = false
#    useSessionStorage = false
#  [privacy.instagram]
#    disable = false
#    simple = false
#  [privacy.twitter]
#    disable = false
#    enableDNT = false
#    simple = false
#  [privacy.vimeo]
#    disable = false
#    enableDNT = false
#    simple = false
#  [privacy.youtube]
#    disable = false
#    privacyEnhanced = false

