baseURL =           "https://andron13.de/"
languageCode =      "ru"
title =             "andron13"
theme =             "book"
disqusShortname =   ""
paginate        =   6

# Book configuration
#disablePathToLower = true
#enableGitInfo = true

[params]
  BookToC = true
  BookLogo = 'logo.jpg'
  BookSection = 'school'
  BookMenuBundle = '/menu'

